### ISSUE TITLE
Ticket Messages - Black Text

### ISSUE THREAD

**Issue by Fot3k** [superstyro/AzerothAdmin#1]
Hi, how can I change the text colour in the tickets tab?

I tried editing the AzerothAdmin.lua but doesn't do anything.

Line:  949

`    for msg in string.gmatch(text, "Ticket Message.-:.-(.*)") do
        MangAdmin.db.account.buffer.ticketread=true
        MangAdmin.db.account.buffer.ticketsfull = {}
        table.remove(MangAdmin.db.account.buffer.ticketsfull, 1)
        --table.insert(MangAdmin.db.account.buffer.ticketsfull, {tMsg = msg})
        table.insert(MangAdmin.db.account.buffer.ticketsfull, {tMsg = " "})
        ma_ticketdetail:SetText("|cffffffff"..msg)
        catchedSth = true
        output = MangAdmin.db.account.style.showchat
    end`

![image](https://user-images.githubusercontent.com/22380279/150620331-f4e8f80f-7c1d-46dc-928c-ae41d4d54966.png)

Thanks for the great addon!

**Comment by superstyro** [comment]
Thanks for the heads up on the issue you are having with the text. 

I am glad you are able to actually use the addon!
