### ISSUE TITLE
Tickets not displaying correctly

### ISSUE THREAD

**Issue by Fot3k** [superstyro/AzerothAdmin#5]
Hi again!

When you load a ticket and then load another ticket in the list, they often show the same message but from different players. It's like it's caching the message and not getting the new tickets when you select from the list.

Would be amazing if this could be looked at please.

Thanks.

**Comment by superstyro** [comment]
I am not able to duplicate this condition with 5 through 16 tickets loaded.

When you click the right side list and the 'Ticket Message' does not update, is there text added to your chat window?

Also, approximately how many tickets are being loaded? Are you using the  'Load All' or 'Load Online' button? Does the list on the right side have enough tickets to have the right side scroll bar?

**Comment by Fot3k** [comment]
Here is a video showing the issue, it also does this in chat except it only shows one ticket in the chat frame and not the other.

https://user-images.githubusercontent.com/22380279/155028389-ee22450c-d72f-40dc-a19a-4524ffe0b4d9.mp4

I would love to re-organize the addon into categories and move some things around. Some commands do not work correctly as well so would need to edit those. What would be the best way to go about this other than editing lua files in notepad++ etc?

Thanks!

**Comment by Warglaive** [comment]
> Here is a video showing the issue, it also does this in chat except it only shows one ticket in the chat frame and not the other.
> 
>  azerothadmin-ticket-issue.mp4 
> I would love to re-organize the addon into categories and move some things around. Some commands do not work correctly as well so would need to edit those. What would be the best way to go about this other than editing lua files in notepad++ etc?
> 
> Thanks!

From what I have read, IntelliJ IDEA can offer a solid development environment + https://plugins.jetbrains.com/plugin/9768-emmylua
