### ISSUE TITLE
Invalid item id: 0

### ISSUE THREAD

**Issue by PentSec** [superstyro/AzerothAdmin#6]
Hello, when i try to add item with [Add] buttom link on lookup list that return.

Invalid item id: 0

any idea to solved it ? 
thanks you.

**Comment by superstyro** [comment]
Are you talking about the line that is added the chat window that looks like this with the [Add] button?

- You create: [Sweetened Goat's Milk] - [Add]  - [List]

This throws error when [Add] clicked in chat window

- Either: "Value '35954:0:0:0:0:0:0:0:1' is not valid for type unsigned int."
- Or:     "Character '35954:0:0:0:0:0:0:0:1' does not exist."

and throws error when [List] is clicked in chat window

- Value '2905:0:0:0:0:0:0:0:1' is not valid for type unsigned int.
